Description: 'CloudFormation template to create an S3 bucket for Terraform state'
Resources:
  TerraformStateBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'terraform-state-jatheesishoh'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  TerraformStateBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref TerraformStateBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EnforceTLSRequestsOnly
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${TerraformStateBucket.Arn}/*'
              - !GetAtt TerraformStateBucket.Arn
            Condition:
              Bool:
                'aws:SecureTransport': false
Outputs:
  BucketName:
    Description: 'Name of the S3 bucket'
    Value: !Ref TerraformStateBucket
  BucketARN:
    Description: 'ARN of the S3 bucket'
    Value: !GetAtt TerraformStateBucket.Arn
